/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banco_tpfinal;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author dante
 */
public class CambioClaveJFrame extends javax.swing.JFrame {

    Registrarse registro;
    Entrada login;
    
    
    /**
     * Creates new form CambioClaveJFrame
     */
    public CambioClaveJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    /**
     * 
     * <p>El parametro recibido (registro) contiene los datos de los usuarios que se hayan 
     * creado gracias al objeto registro de la clase Registrarse.</p>
     * <p>El parametro recibido (login) contiene los datos del usuario al cual se  
     * le aplicará el cambio de clave.</p>
     * <p>los parametros se trajeron desde el JFrame "Operaciones" </p>
     * @param registro 
     * @param login 
     */
    public CambioClaveJFrame(Registrarse registro,Entrada login){
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.registro = registro;
        this.login = login;
        
    }

    
    /**
     * 
     * <p>"nuevaClave()" : Funcion que realiza el cambio de contraseña.</p>
     * @return Descripcion: Retorna un valor boolean que indicará si se realizó 
     * el cambio de contraseña o si no se realizó. 
     */
    public boolean nuevaClave(){
        Operaciones op = new Operaciones(registro, login);
        
        if(registro.listaClientes.get(op.codigo).getContra().equals(txtContraVieja.getText())){
            if (!txtContraNueva.getText().isEmpty()){    
                if (txtContraNueva.getText().equals(txtRepetirContra.getText())){
                    registro.listaClientes.get(op.codigo).setContra(txtContraNueva.getText());
                    JOptionPane.showMessageDialog(rootPane, "cambio de contraseña realizado con éxito");
                    JOptionPane.showMessageDialog(rootPane, "Nueva contraseña: "+registro.listaClientes.get(op.codigo).contra);
                    return true;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "La nueva contraseña no es igual a la repetida,\n no se realizó el cambio de contraseña", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtRepetirContra.setText(null);
                    txtRepetirContra.requestFocus();
                    return false;
                }
            } else {
                 JOptionPane.showMessageDialog(rootPane, "No puede dejar el campo 'Nueva Contraseña' vacío,\n ingrese una nueva contraseña para realizar el cambio de contraseña", "ERROR", JOptionPane.ERROR_MESSAGE);
                 txtContraNueva.setText(null);
                 txtContraNueva.requestFocus();
                 return false;
                }
        } else {
            JOptionPane.showMessageDialog(rootPane, "La contraseña actual no es la correcta,\n no se realizó el cambio de clave", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtContraVieja.setText(null);
            txtContraVieja.requestFocus();
            return false;
        } 
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtContraVieja = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtRepetirContra = new javax.swing.JPasswordField();
        txtContraNueva = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setInheritsPopupMenu(true);

        btnAceptar.setBackground(new java.awt.Color(0, 204, 51));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña vieja");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 153, 153));
        jLabel4.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nueva contraseña");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Repetir contraseña");
        jLabel5.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAMBIAR CONTRASEÑA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        txtContraVieja.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtContraVieja.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContraVieja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraViejaKeyPressed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 56, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtRepetirContra.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtRepetirContra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRepetirContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRepetirContraKeyPressed(evt);
            }
        });

        txtContraNueva.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtContraNueva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContraNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraNuevaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContraVieja)
                            .addComponent(txtRepetirContra)
                            .addComponent(txtContraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContraVieja)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraNueva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRepetirContra)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try{
            boolean bien = nuevaClave();
            if (bien) {
                this.setVisible(false);
                Operaciones op = new Operaciones(registro, login);    // Necesito "registro" y "login" para actualizar los datos.
                op.setVisible(true);
                op.repaint();
                op.validate();
            }

        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e+"\n\nTienes que iniciar sesión antes", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtContraViejaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraViejaKeyPressed

        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
            txtContraNueva.requestFocus();
        }

    }//GEN-LAST:event_txtContraViejaKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        try{
            Operaciones op = new Operaciones(registro, login);
            this.setVisible(false);
            op.setVisible(true);
            op.repaint();
            op.validate();
        }catch(NullPointerException e1){
            JOptionPane.showMessageDialog(rootPane, e1+"\n\nTienes que iniciar sesión antes", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtRepetirContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepetirContraKeyPressed

        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){

            btnAceptar.doClick();

        }

    }//GEN-LAST:event_txtRepetirContraKeyPressed

    private void txtContraNuevaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNuevaKeyPressed

        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
            txtRepetirContra.requestFocus();
        }

    }//GEN-LAST:event_txtContraNuevaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioClaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioClaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioClaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioClaveJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioClaveJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraNueva;
    private javax.swing.JTextField txtContraVieja;
    private javax.swing.JPasswordField txtRepetirContra;
    // End of variables declaration//GEN-END:variables
}
