/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banco_tpfinal;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dante
 */
public class Operaciones extends javax.swing.JFrame {

    
    Registrarse registro;
    Entrada login = new Entrada();
    int codigo = 0;
    DateFormat modificarFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    
    
    
    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    
    /**
     * 
     * <p>El parametro recibido (registro) contiene los datos de los usuarios que se hayan 
     * creado gracias al objeto registro de la clase Registrarse.</p>
     * <p>El parametro recibido (login) contiene los datos del usuario al cual se  
     * le aplicarán los movimientos de dinero.</p>
     * @param registro 
     * @param login 
     */
    public Operaciones(Registrarse registro, Entrada login){
        initComponents();
        this.registro = registro;
        this.login = login;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        codigo = registro.buscar(login.user);
        txtAreaUsuario.setText(registro.listaClientes.get(codigo).mostrarDatos());
    }
    
    /**
     * 
     * <p>El parametro recibido (registro) contiene los datos de los usuarios que 
     * se hayan creado gracias al objeto registro de la clase Registrarse.</p>
     * <p>El parametro recibido (login) contiene los datos del usuario al cual se  
     * le aplicarán los cambios en su cuenta.</p>
     * <p> El método "actualizarClave(Registrarse registro, Entrada login)" trae
     * los datos desde el JFrame "Entrada" y los instancia en el JFrame "Operaciones"
     * para que luego esten disponibles cuando se quiera realizar el cambio de contraseña
     * </p>
     * 
     * @param registro 
     * @param login 
     */
    public void actualizarClave(Registrarse registro, Entrada login){
        this.registro = registro;
        this.login = login;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaUsuario = new javax.swing.JTextArea();
        btnCerrarSesion = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnConsultarMovimientos = new javax.swing.JButton();
        btnCambiarClave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setInheritsPopupMenu(true);

        btnConsultar.setBackground(new java.awt.Color(225, 236, 244));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(102, 102, 102));
        btnConsultar.setText("Consultar Saldo");
        btnConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtAreaUsuario.setEditable(false);
        txtAreaUsuario.setBackground(new java.awt.Color(255, 102, 51));
        txtAreaUsuario.setColumns(20);
        txtAreaUsuario.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        txtAreaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaUsuario.setLineWrap(true);
        txtAreaUsuario.setRows(2);
        txtAreaUsuario.setTabSize(4);
        txtAreaUsuario.setText("\n");
        txtAreaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtAreaUsuario.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        txtAreaUsuario.setFocusable(false);
        txtAreaUsuario.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txtAreaUsuario);

        btnCerrarSesion.setBackground(new java.awt.Color(255, 168, 168));
        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnRetirar.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnDepositar.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnDepositar.setText("Depositar");
        btnDepositar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 2));
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnConsultarMovimientos.setBackground(new java.awt.Color(225, 236, 244));
        btnConsultarMovimientos.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnConsultarMovimientos.setForeground(new java.awt.Color(102, 102, 102));
        btnConsultarMovimientos.setText("Movimientos");
        btnConsultarMovimientos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMovimientosActionPerformed(evt);
            }
        });

        btnCambiarClave.setBackground(new java.awt.Color(225, 236, 244));
        btnCambiarClave.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnCambiarClave.setForeground(new java.awt.Color(102, 102, 102));
        btnCambiarClave.setText("Cambiar clave");
        btnCambiarClave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarClaveActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPERACIONES");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConsultarMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCambiarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
/*El saldo se muestra en el area que esta arriba de los botones */
        String fila = "";
        System.out.println(codigo);
        String[] opciones = {"Mostrar en Pantalla", "Imprimir ticket"};
        
        
        int eleccion = JOptionPane.showOptionDialog(rootPane, "CONSULTAR SALDO","BANCO SANTANDER",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);

        switch (eleccion) {
            case 0:
                try{
                    txtAreaUsuario.setText(null);

                    fila = registro.listaClientes.get(codigo).mostrarDatos();
                    txtAreaUsuario.append(fila);

                }catch(NullPointerException e1){
                    JOptionPane.showMessageDialog(this, e1.getMessage() + "\n\nEl usuario no ha iniciado sesion", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            break;
            case 1:
                txtAreaUsuario.setText("======================================="
                    + "\n\nno hay papel"
                    + "\n\nno se puede imprimir el comprobante");
            break;
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed

        this.setVisible(false);
        login.setVisible(true);
        login.repaint();
        login.validate();

    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed

        try{

            txtAreaUsuario.setText(null);
            float retira = 0f;

            retira = Float.parseFloat(JOptionPane.showInputDialog(this, "Ingresa la cantidad a retirar", "Cantidad", JOptionPane.QUESTION_MESSAGE ));

            if (retira >= 1 ){
                if (registro.listaClientes.get(codigo).cuenta > retira){

                    registro.listaClientes.get(codigo).retirar(retira);
                    JOptionPane.showMessageDialog(this, "Retiro realizado", "OPERACION EXITOSA!", JOptionPane.INFORMATION_MESSAGE);

                    String resumen = "======================="
                    + "\nRetiro realizado con éxito"
                    + "\n\nSu saldo es: "+registro.listaClientes.get(codigo).cuenta;

                    txtAreaUsuario.append(resumen);

                    // INGRESAR MOVIMIENTO
                    Date fecha = new Date();
                    String mov = "Retiro ------ "+String.valueOf(retira)+ " AR$ ----- "+modificarFecha.format(fecha);
                    registro.listaClientes.get(codigo).ingresarMovimiento(mov);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falta de fondos,\n no puede retirar esa cantidad ", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "El retiro debe de ser mayor o igual a 1 ", "ERROR", JOptionPane.WARNING_MESSAGE);
            }

        }catch(NumberFormatException e1){
            JOptionPane.showMessageDialog(rootPane, e1.getMessage() + "\n\nLos valores para retirar deben ser numéricos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }catch (NullPointerException e2) {
            JOptionPane.showMessageDialog(rootPane, e2.getMessage()+ "\n\nEl retiro se canceló por no ingresar datos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed

        try{
            txtAreaUsuario.setText(null);
            float Depo = 0f;
            float DepoR = 0f;
            int tipo = -1;
            String mov = "";

            String[] deposito = {"Efectivo", "Cheque","CANCELAR"};

            tipo = JOptionPane.showOptionDialog(rootPane, "Depositos con cheque"
                + "\nTienen 5% de recargo", "DEPOSITO", JOptionPane.OK_CANCEL_OPTION, JOptionPane.DEFAULT_OPTION, null, deposito, deposito[0]);

            if (tipo >= 0 && tipo != 2){

                Depo = Float.parseFloat(JOptionPane.showInputDialog(this, "Ingresa la cantidad a depositar", "Cantidad", JOptionPane.QUESTION_MESSAGE ));

                if (Depo >= 1){

                    if(tipo == 1){

                        Depo = Depo;
                        DepoR = Depo *0.95f;
                        registro.listaClientes.get(codigo).depositar(DepoR);
                        JOptionPane.showMessageDialog(this, "Deposito realizado"
                            + "\ncantidad del depósito: "+DepoR+"\nComision: "+Depo*0.05, "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);

                        // INGRESAR MOVIMIENTO
                        Date fecha = new Date();
                        mov = "Deposito ------ "+String.valueOf(DepoR) + " AR$ ----- "+modificarFecha.format(fecha)+
                        "\nmonto: "+Depo+"\nComision: "+Depo*0.05;
                    } else {

                        registro.listaClientes.get(codigo).depositar(Depo);
                        JOptionPane.showMessageDialog(this, "Deposito realizado"
                            + "\ncantidad del depósito: "+Depo, "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
                        Date fecha = new Date();
                        mov = "Deposito ------ "+String.valueOf(Depo) + " AR$ ----- "+modificarFecha.format(fecha)+
                        "\nmonto: "+Depo+"\nComision: "+0;
                    }

                    String resumen = "======================="
                    + "\nDeposito realizado con éxito"
                    + "\n\nsu saldo es: "+registro.listaClientes.get(codigo).cuenta;

                    txtAreaUsuario.append(resumen);
                    registro.listaClientes.get(codigo).ingresarMovimiento(mov);

                } else{
                    JOptionPane.showMessageDialog(rootPane, "La cantidad a depositar debe de ser mayor o igual a 1", "ERROR", JOptionPane.WARNING_MESSAGE);
                }

            }
        }catch (NumberFormatException e1){
            JOptionPane.showMessageDialog(rootPane, e1.getMessage()+ "\n\nLos valores a depositar deben ser numéricos", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e2) {
            JOptionPane.showMessageDialog(rootPane, e2.getMessage()+ "\n\nEl deposito se canceló", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnConsultarMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMovimientosActionPerformed

        try{
            txtAreaUsuario.setText(null);
            txtAreaUsuario.append(registro.listaClientes.get(codigo).mostrarMovimientos());
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e + "\n\nDebes de iniciar sesion", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConsultarMovimientosActionPerformed

    private void btnCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarClaveActionPerformed

        CambioClaveJFrame cc = new CambioClaveJFrame(registro, login);
        this.setVisible(false);
        
        cc.setVisible(true);
        cc.repaint();
        cc.validate();

    }//GEN-LAST:event_btnCambiarClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarClave;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarMovimientos;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaUsuario;
    // End of variables declaration//GEN-END:variables
}
